### ISSUE TITLE
Remove duplicate tweets on partial match....look into installing Lodash for _uniq function

### ISSUE THREAD

**Issue by csturco0331** [TeamSlowTrack/Third-Assessment#21]

**Comment by MilesNeitz** [comment]
change tweetsRepo.findTweetsByHashtags_LabelContainingAndDeletedFlagFalseOrderByPostedDesc(label);
to tweetsRepo.findDistinctTweetsByHashtags_LabelContainingAndDeletedFlagFalseOrderByPostedDesc(label);
